site_name: 'Cloud Native Security Tutorial'
site_description: 'Getting started with cloud native security'
site_author: 'Liz Rice and Michael Hausenblas'
repo_name: 'k8s-sec/cloud-native-security-tutorial'
repo_url: 'https://github.com/k8s-sec/cloud-native-security-tutorial'
copyright: 'Copyright &copy; Liz Rice and Michael Hausenblas'
docs_dir: 'docs'
nav:
    - Home:
      - Overview: index.md
      - Introduction: introduction.md
      - Preparation: preparation.md
    - Exercises:
      - Compromised pod: compromise.md
      - Scanning: scanning.md
      - Policies: policies.md
      - Secure settings: settings.md
      - GitOps: gitops.md
    - Conclusion:
      - conclusions.md
theme:
    name: 'material'
    features:
    - 'tabs'
    - 'instant'
    icon:
        logo: 'material/lock'
    font:
      text: 'Lato'
      code: 'PT Mono'
    palette:
      primary: 'blue'
      accent: 'orange'
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true

